insert into modulos (trilha_id, ordem, slug, titulo, duracao_min, video_youtube_id, video_playlist_id, video_titulo, video_canal, video_resumo, atividade_tipo, atividade_titulo, atividade_dica, atividade_config, lembrar)
values ((select id from trilhas where ordem = 1), 1, 'm1', 'Renda extra pela internet', 5, 'zmISrAl8h24', null, 'Renda extra com aplicativos', 'Serasa Ensina', 'Aplicativos e plataformas online podem render uma renda extra, mas é preciso conferir se são seguros e desconfiar de promessas de lucro alto e fácil.', 'classificar', 'Parece seguro ou é sinal de alerta?', 'Toque na opção de cada situação.', '{"opcoes":["Parece seguro","Sinal de alerta"],"itens":[["Promete lucro muito alto e fácil",1],["Pede um pagamento antecipado para liberar seus ganhos",1],["Tem CNPJ, regras claras e um canal de atendimento que você consegue conferir",0],["Pede a senha do seu banco",1],["Não cobra nada para participar e explica como o pagamento funciona",0]]}'::jsonb, array['Aplicativos e plataformas online podem gerar renda extra.', 'Antes de se cadastrar, confira se a plataforma é segura e verdadeira.', 'Desconfie de promessas de lucro muito alto e fácil.']);
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm1'), 1, 'bag', 'Renda além do salário', 'Renda extra é todo dinheiro que entra além da sua renda principal. Hoje, aplicativos e plataformas online são um caminho possível para conseguir essa renda.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm1'), 2, 'lock', 'Confira antes de se cadastrar', 'Veja se a plataforma é segura e verdadeira: pesquise o nome, confira se existe canal de atendimento e nunca passe a senha do seu banco.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm1'), 3, 'bell', 'Desconfie do lucro fácil', 'Promessas de ganhar muito, rápido e sem esforço são o sinal de alerta mais comum de golpe. Plataforma séria não costuma pedir pagamento antecipado para liberar seus ganhos.');
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm1'), 1, 'Segundo a aula, uma possibilidade de conseguir renda extra é:', 'Aplicativos e plataformas online são uma das formas de conseguir renda extra.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 1), 1, 'Utilizar aplicativos e plataformas online', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 1), 2, 'Fazer empréstimos frequentemente', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 1), 3, 'Aumentar o limite do cartão', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 1), 4, 'Deixar de pagar contas', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm1'), 2, 'O que deve ser feito antes de se cadastrar em uma plataforma de renda extra?', 'Conferir se a plataforma é segura e verdadeira ajuda a evitar golpes.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 2), 1, 'Compartilhar seus dados com qualquer pessoa', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 2), 2, 'Verificar a segurança e a veracidade da plataforma', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 2), 3, 'Fazer um pagamento antecipado', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 2), 4, 'Informar sua senha bancária', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm1'), 3, 'O vídeo alerta que é importante desconfiar de:', 'Promessas de lucro muito alto e fácil são um sinal clássico de golpe.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 3), 1, 'Plataformas conhecidas', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 3), 2, 'Promessas de lucros muito altos e fáceis', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 3), 3, 'Pesquisas online', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm1' and pq.ordem = 3), 4, 'Trabalho pela internet', false);

insert into modulos (trilha_id, ordem, slug, titulo, duracao_min, video_youtube_id, video_playlist_id, video_titulo, video_canal, video_resumo, atividade_tipo, atividade_titulo, atividade_dica, atividade_config, lembrar)
values ((select id from trilhas where ordem = 1), 2, 'm2', 'O ciclo da dívida', 5, 'UEiBsd_nmTA', null, 'O ciclo da dívida', 'Serasa Ensina', 'O ciclo da dívida passa pelo atraso no pagamento, pela cobrança da empresa credora e pela possível negativação, quando a Serasa entra para comunicar e registrar informações de crédito.', 'classificar', 'Quem faz o quê?', 'Toque em quem é responsável por cada ação.', '{"opcoes":["Empresa credora","Serasa"],"itens":[["Concedeu o crédito e cobra a dívida",0],["Solicita a negativação da dívida",0],["Comunica o consumidor sobre a possível negativação",1],["Registra as informações de crédito",1]]}'::jsonb, array['O atraso no pagamento é uma das primeiras etapas do ciclo da dívida.', 'Quem solicita a negativação é a empresa credora.', 'A Serasa comunica a possível negativação e registra informações de crédito.']);
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm2'), 1, 'bag', 'Tudo começa no crédito', 'Ao comprar parcelado, usar o cartão ou pegar um empréstimo, você assume uma dívida. Pagando em dia, o ciclo termina por aí.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm2'), 2, 'bell', 'O atraso é uma das primeiras etapas', 'Quando o pagamento atrasa, a conta passa a ser cobrada e a dívida começa a crescer. É uma das primeiras etapas do ciclo da dívida.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm2'), 3, 'category', 'Quem faz o quê', 'Quem pode pedir a negativação é a empresa credora. A Serasa comunica o consumidor sobre a possível negativação e registra informações de crédito.');
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm2'), 1, 'Qual é uma das primeiras etapas do ciclo de uma dívida?', 'O atraso no pagamento é uma das primeiras etapas do ciclo da dívida.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 1), 1, 'Atrasar o pagamento', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 1), 2, 'Aumentar o salário', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 1), 3, 'Cancelar o CPF', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 1), 4, 'Receber um empréstimo', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm2'), 2, 'Quem solicita a negativação de uma dívida?', 'É a empresa credora, que concedeu o crédito, quem solicita a negativação.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 2), 1, 'O consumidor', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 2), 2, 'A empresa credora', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 2), 3, 'O banco central', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 2), 4, 'O consumidor junto à Serasa', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm2'), 3, 'Por que a Serasa entra na relação entre consumidor e empresa credora?', 'A Serasa comunica sobre a possível negativação e registra informações de crédito.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 3), 1, 'Para criar a dívida', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 3), 2, 'Para comunicar sobre a possível negativação e registrar informações de crédito', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 3), 3, 'Para escolher o valor da dívida', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm2' and pq.ordem = 3), 4, 'Para definir o salário do consumidor', false);

insert into modulos (trilha_id, ordem, slug, titulo, duracao_min, video_youtube_id, video_playlist_id, video_titulo, video_canal, video_resumo, atividade_tipo, atividade_titulo, atividade_dica, atividade_config, lembrar)
values ((select id from trilhas where ordem = 1), 3, 'm3', 'Atrasada, negativada ou caducada?', 5, 'CkwxlovFIa0', null, 'Dívida atrasada, negativada ou caduca: qual a diferença?', 'Serasa Ensina', 'Dívida atrasada é a que passou do vencimento. A negativada é registrada nos birôs. A caducada pode deixar de aparecer nos birôs depois de cinco anos, mas a pendência continua com a empresa.', 'classificar', 'Qual é qual?', 'Toque no tipo de dívida de cada situação.', '{"opcoes":["Atrasada","Negativada","Caducada"],"itens":[["Venceu ontem e ainda não foi paga",0],["Seu nome foi registrado nos birôs por causa da dívida",1],["Passou de cinco anos e deixou de aparecer nos birôs, mas a pendência segue com a empresa",2],["Pode gerar juros enquanto não for paga",0]]}'::jsonb, array['Atrasada: não foi paga até o vencimento.', 'Negativada: o nome foi registrado nos birôs de crédito.', 'Caducada: pode sair dos birôs depois de cinco anos, mas a pendência continua com a empresa.']);
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm3'), 1, 'note', 'Dívida atrasada', 'É a conta que não foi paga até a data de vencimento. Enquanto continua em aberto, ela pode gerar juros.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm3'), 2, 'lock', 'Dívida negativada', 'Quando a empresa credora pede, o nome do consumidor pode ser registrado nos birôs de crédito por causa da dívida em atraso.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm3'), 3, 'star', 'Dívida caducada', 'Depois de cinco anos, a dívida pode deixar de aparecer nos birôs de crédito. Mas atenção: a pendência continua existindo com a empresa.');
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm3'), 1, 'O que caracteriza uma dívida atrasada?', 'Dívida atrasada é a conta que não foi paga até a data do vencimento.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 1), 1, 'Uma conta que ainda não venceu', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 1), 2, 'Uma conta que não foi paga até a data de vencimento', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 1), 3, 'Uma dívida que foi automaticamente cancelada', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 1), 4, 'Uma dívida que nunca existiu', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm3'), 2, 'O que pode acontecer com uma dívida atrasada?', 'A dívida atrasada pode gerar juros enquanto não for paga.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 2), 1, 'Ela pode gerar juros', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 2), 2, 'Ela desaparece imediatamente', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 2), 3, 'O consumidor recebe dinheiro', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 2), 4, 'O limite do cartão aumenta', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm3'), 3, 'Depois de cinco anos, uma dívida simplesmente deixa de existir?', 'Ela pode sair dos birôs, mas a pendência continua existindo com a empresa.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 3), 1, 'Sim, sempre', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 3), 2, 'Não, a dívida pode deixar de aparecer nos birôs de crédito, mas a pendência continua existindo com a empresa', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 3), 3, 'Sim, desde que o consumidor não consulte o CPF', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm3' and pq.ordem = 3), 4, 'Sim, automaticamente após cinco anos', false);

insert into modulos (trilha_id, ordem, slug, titulo, duracao_min, video_youtube_id, video_playlist_id, video_titulo, video_canal, video_resumo, atividade_tipo, atividade_titulo, atividade_dica, atividade_config, lembrar)
values ((select id from trilhas where ordem = 1), 4, 'm4', 'O que é amortização?', 5, '7Ib1rTuxUpk', null, 'O que é amortização? (Falando Dinheirês)', 'Serasa Ensina', 'Amortizar é pagar uma parte da dívida para reduzir o valor devido, diminuindo o saldo devedor.', 'amortizar', 'Veja o saldo devedor diminuir', 'Mude os valores e veja quanto falta pagar.', null, array['Amortizar é reduzir o valor devido por meio de pagamentos.', 'A amortização está ligada à redução de uma dívida.', 'Ao amortizar, o saldo devedor pode diminuir.']);
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm4'), 1, 'trophy', 'Amortizar é reduzir a dívida', 'Amortizar é pagar uma parte do que você deve para diminuir o valor devido.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm4'), 2, 'sprout', 'O saldo devedor diminui', 'Saldo devedor é quanto ainda falta pagar. Ao amortizar, ele pode diminuir.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm4'), 3, 'check', 'Por que isso importa', 'Quanto mais você amortiza, menos falta para quitar. É um caminho para sair da dívida.');
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm4'), 1, 'O que significa amortizar uma dívida?', 'Amortizar é reduzir o valor devido por meio de pagamentos.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 1), 1, 'Aumentar o valor da dívida', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 1), 2, 'Reduzir o valor devido por meio de pagamentos', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 1), 3, 'Cancelar uma dívida automaticamente', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 1), 4, 'Parar de pagar as parcelas', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm4'), 2, 'A amortização está relacionada principalmente a:', 'A amortização está ligada à redução de uma dívida.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 2), 1, 'Redução de uma dívida', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 2), 2, 'Aumento do salário', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 2), 3, 'Criação de uma conta bancária', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 2), 4, 'Aumento do limite do cartão', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm4'), 3, 'Ao amortizar uma dívida, o que pode acontecer com o saldo devedor?', 'Ao amortizar, o saldo devedor pode diminuir.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 3), 1, 'Pode diminuir', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 3), 2, 'Sempre aumenta', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 3), 3, 'Desaparece imediatamente', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm4' and pq.ordem = 3), 4, 'Não sofre nenhuma alteração', false);

insert into modulos (trilha_id, ordem, slug, titulo, duracao_min, video_youtube_id, video_playlist_id, video_titulo, video_canal, video_resumo, atividade_tipo, atividade_titulo, atividade_dica, atividade_config, lembrar)
values ((select id from trilhas where ordem = 1), 5, 'm5', 'Juros de mora', 5, 'Yic1w81yBq8', null, 'Juros de mora (Falando Dinheirês)', 'Serasa Ensina', 'Juros de mora são cobrados pelo atraso no pagamento de uma conta e podem aumentar quanto maior for o tempo de atraso.', 'mora', 'Veja o atraso custando mais', 'Mexa nos dias de atraso e compare o valor final.', null, array['Juros de mora são cobrados pelo atraso no pagamento.', 'Quanto maior o atraso, maior pode ser o valor dos juros.', 'Pagar dentro do prazo evita essa cobrança.']);
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm5'), 1, 'bell', 'Os juros do atraso', 'Juros de mora são cobrados pelo atraso no pagamento de uma conta. Quem paga dentro do prazo não paga esses juros.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm5'), 2, 'category', 'Crescem com o tempo', 'Quanto maior o período de atraso, maior pode ficar o valor dos juros.');
insert into modulo_cartoes (modulo_id, ordem, icone, titulo, texto) values ((select id from modulos where slug = 'm5'), 3, 'check', 'Como evitar', 'Pague as contas dentro do prazo. Se for atrasar, resolva o quanto antes para o custo não crescer.');
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm5'), 1, 'O que são juros de mora?', 'Juros de mora são cobrados pelo atraso no pagamento.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 1), 1, 'Juros cobrados quando uma conta é paga antes do vencimento', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 1), 2, 'Juros cobrados pelo atraso no pagamento de uma conta', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 1), 3, 'Desconto oferecido para pagamentos antecipados', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 1), 4, 'Taxa cobrada somente na abertura de uma conta', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm5'), 2, 'O que pode acontecer com os juros de mora conforme aumenta o período de atraso?', 'Quanto maior o período de atraso, maior pode ficar o valor dos juros.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 2), 1, 'O valor dos juros pode aumentar', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 2), 2, 'Os juros desaparecem automaticamente', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 2), 3, 'A dívida é cancelada', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 2), 4, 'O valor da conta diminui', false);
insert into perguntas_quiz (modulo_id, ordem, enunciado, explicacao) values ((select id from modulos where slug = 'm5'), 3, 'Qual atitude ajuda a evitar a cobrança de juros de mora?', 'Pagar dentro do prazo evita a cobrança de juros de mora.');
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 3), 1, 'Deixar as contas para depois', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 3), 2, 'Pagar as contas dentro do prazo', true);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 3), 3, 'Utilizar todo o limite do cartão', false);
insert into alternativas (pergunta_id, ordem, texto, correta) values ((select pq.id from perguntas_quiz pq join modulos mo on mo.id = pq.modulo_id where mo.slug = 'm5' and pq.ordem = 3), 4, 'Ignorar a data de vencimento', false);

